# Generated by Django 4.2.7 on 2025-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastjob',
            name='forecast_horizon',
            field=models.PositiveIntegerField(default=24, help_text='Number of hours forecasted in this job'),
        ),
    ]
