# Generated by Django 4.2.7 on 2025-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_forecastjob_forecast_horizon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('hydro', 'Hydro')], help_text='Type of renewable energy site', max_length=50),
        ),
    ]
